### PR TITLE
Prevent clobbering error stack trace

### LINKED ISSUE #25: prototype = new Error() call causes problems
Not quite sure why, but it's apparently an issue:

```
Error
    at Object.<anonymous> (/usr/lib/node_modules/cli/node_modules/superagent-bluebird-promise/index.js:16:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/cli/lib/install.js:15:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at attemptRequire (/usr/lib/node_modules/cli/node_modules/attempt-require/index.js:6:20)
    at Object.<anonymous> (/usr/lib/node_modules/cli/bin/cli.js:39:15)
```

### PR DESCRIPTION
**Pull request by spudly**
Fixes #25

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -38,13 +28,15 @@ Request.prototype.promise = function() {
       req.end(function(err, res) {
         if (typeof res !== "undefined" && res.status >= 400) {
           var msg = 'cannot ' + req.method + ' ' + req.url + ' (' + res.status + ')';
-          error = new SuperagentPromiseError(msg);
+          error = new Error(msg || 'Bad request');
```
Comment (KyleAMathews) [inline index.js]: msg will always exist here
